spring:
  application:
    name: catalog
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:catalog
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
  h2:
    console:
      enabled: true
