version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${CATALOG_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CATALOG_POSTGRES_PASSWORD}
      POSTGRES_DB: decor-manager.catalog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catalog-app
    depends_on:
       - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ["./mvnw", "spring-boot:run"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/decor-manager.catalog
      SPRING_DATASOURCE_USERNAME: ${CATALOG_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${CATALOG_POSTGRES_PASSWORD}
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

volumes:
  postgres_data: